GET http://127.0.0.1:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOiJJcWJhbCIsImVtYWlsIjoiaXFiYWxAZ21haWwuY29tIiwiaWF0IjoxNzIxODkxMDkyLCJleHAiOjE3MjE4OTExMTJ9.7HIb2O6uL6W9Ymus86K574MmX-5GRWX_3wf3det1Xic


###
POST http://127.0.0.1:5000/users
Content-Type: application/json

{
    "name": "Iqbal",
    "email": "iqbal@gmail.com",
    "password" : "123456",
    "confPassword": "123456"
}

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "email": "iqbal@gmail.com",
    "password" : "123456"
}


